[tool.poetry]
name = "sassha"
version = "0.1.0"
description = ""
authors = ["LoboGuardian <loboguardian.dev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
paramiko = "^3.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
